language: java
jdk:
  - oraclejdk8
before_install:
  # Unset the Java options to avoid errors in build
  # https://github.com/travis-ci/travis-ci/issues/8408
  # https://github.com/rspec/rspec-dev/pull/185
  - unset _JAVA_OPTIONS
install:
  - mvn clean install -B -q -DskipTests -Dcheckstyle.skip
script:
  - mvn clean install
